### ISSUE TITLE
image does not appear to support vendoring

### ISSUE THREAD

**Issue by btc** [GoogleCloudPlatform/golang-docker#127]
I am using the app engine flex environment.

When I deploy, the cloud build fails:

```
Step 3/3 : RUN go-wrapper install -tags appenginevm
---> Running in e3aebcd0fd0e
exec go install -v -tags appenginevm
main.go:10:2: cannot find package "github.com/gorilla/mux" in any of:
/usr/local/go/src/github.com/gorilla/mux (from $GOROOT)
/go/src/github.com/gorilla/mux (from $GOPATH)
/go/src/app/_gopath/src/github.com/gorilla/mux
The command '/bin/sh -c go-wrapper install -tags appenginevm' returned a non-zero code: 1
ERROR
ERROR: build step "gcr.io/cloud-builders/docker@sha256:c99ef71791f407f8d2deaf782feceb00f4c5b59d0e8f7e50160acf9dd638d6failed: exit status 1
```
I checked the archive used to build the container. The code in question is in:

`_gopath/src/github.com/btc/apartment-service/vendor/github.com/gorilla/mux`

```
apartment-service (master) λ. gcloud  version                                                                                                                                                                  2
Google Cloud SDK 179.0.0
app-engine-go
app-engine-python 1.9.62
beta 2017.09.15
bq 2.0.27
core 2017.11.06
gcloud
gsutil 4.28
kubectl
```

**Comment by cybrcodr** [comment]
Can you try the beta build pipeline?  The latest beta build pipeline should be able to handle vendor and internal directories.

See announcement for what's different with this beta build pipeline --
https://groups.google.com/forum/#!msg/google-appengine-go/cG_JAAX73Zg/27wXKI7aBQAJ

I'd recommend using latest gcloud version 179.0.0 as it does contain the support for vendor/internal directories.

Do let me know if you run into other issues.
