### ISSUE TITLE
Error: Missing Git

### ISSUE THREAD

**Issue by thurt** [GoogleCloudPlatform/golang-docker#131]
Relevant lines from build output:
```
Building server
Step 1/7 : FROM gcr.io/google-appengine/golang:1.8
1.8: Pulling from google-appengine/golang
Digest: sha256:21a08fb893abcca05d8c39b71d10c56ab9a13120b86f61d498c986a1de6b5cd1
Status: Downloaded newer image for gcr.io/google-appengine/golang:1.8
 ---> dd65085f4df4
Step 2/7 : WORKDIR /go/src/app
 ---> 84977f9774c0
Removing intermediate container 9c757579198e
Step 3/7 : COPY . .
 ---> cb7ed7afc0a4
Step 4/7 : RUN go-wrapper download
 ---> Running in 2743dd18164c
+ exec go get -v -d
github.com/go-sql-driver/mysql (download)
go: missing Git command. See https://golang.org/s/gogetcmd
```

my Dockerfile
```
FROM gcr.io/google-appengine/golang:1.8

WORKDIR /go/src/app
COPY . .

RUN go-wrapper download
RUN go-wrapper install

CMD ["go-wrapper", "run"]
```

I just switched to this base image and ran into this issue. Previously, I was using `golang:1.8` base image and everything worked fine. a side Q: what's the difference b/w the gcr.io golang image and the official `golang:1.8`?

**Comment by cybrcodr** [comment]
`go-wrapper download` command requires git.  The image `gcr.io/google-appengine/golang` does not contain git.  Looking at the [golang](https://github.com/docker-library/golang/blob/87aaffce8f74bc5bee1306539030ee413c32aee4/1.8/jessie/Dockerfile) image,  its base image [buildpack-deps:jessie-scm](https://github.com/docker-library/buildpack-deps/blob/1845b3f918f69b4c97912b0d4d68a5658458e84f/jessie/scm/Dockerfile) does contain git.

`gcr.io/google-appengine/golang` image is meant for building AppEngine Flex applications where the assumption is that all Go source files including dependencies are locally present.

**Comment by thurt** [comment]
Thank you!

i guess i'm still confused, is `gcr.io/google-appengine/golang` required for deploying to GAE flex? docs seem to suggest that [here](https://cloud.google.com/appengine/docs/flexible/custom-runtimes/build#create_a_dockerfile). if it is required, my question is what does it include that makes it required?

**Comment by cybrcodr** [comment]
Nope, unless your app actually uses the Go SDK and other Unix binaries during runtime.  If you are using a custom runtime, you can use a Dockerfile that will produce a minimal set of binaries/files for your app's runtime.  That page describes the simplest approach to get a Go binary in a Docker image, but the resulting app image will contain a lot more than necessary.

Go App Engine Flex beta currently uses a different build pipeline that will produce an application image w/o containing the Go SDK nor the standard Unix binaries.  See [announcement here](https://groups.google.com/forum/#!msg/google-appengine-go/cG_JAAX73Zg/27wXKI7aBQAJ).

If you are deploying on Flex, do give it a try.  If you are not deploying on Flex, but would like to reuse the new builder image, [this readme](https://github.com/GoogleCloudPlatform/golang-docker/tree/master/runtime-builder) shows a simple example.
