### ISSUE TITLE
add multiple compile target for google/golang

### ISSUE THREAD

**Issue by proppy** [GoogleCloudPlatform/golang-docker#14]
The default should be:
`google/golang:1.2.2.linux-amd64`

But we could also provide other flavor for cross compilation purpose, ex:
`google/golang:1.2.2.darwin-amd64`

Or even one with all target built from sources:
`google/golang:1.2.2.all`

We could switch to building from sources as there should be little to no overhead in the image size (we already need `build-essentials` for cgo).

**Comment by gmlewis** [comment]
The google/golang* Docker images have been deprecated in favor of the official Docker Go images:
https://hub.docker.com/_/golang/
Closing issue.
