### ISSUE TITLE
missing gcc / build tools in image

### ISSUE THREAD

**Issue by bendory** [GoogleCloudPlatform/golang-docker#141]
context: https://stackoverflow.com/questions/51353818/exec-gcc-executable-file-not-found-in-path/51365908?noredirect=1#comment89716741_51365908

**Comment by cybrcodr** [comment]
We did intend this image to be minimal.  Given that one can easily use their own Dockerfile for a custom runtime on GAE Flex, I'd suggest using a multi-stage Dockerfile and use the Go runtime builder image for the Go SDK part.  One can bring in their own C++ toolchain via a different image.

See https://github.com/GoogleCloudPlatform/golang-docker/tree/master/runtime-builder#multi-stage-dockerfile.
