### ISSUE TITLE
ENV GOROOT?  Dave does not approve...

### ISSUE THREAD

**Issue by tianon** [GoogleCloudPlatform/golang-docker#23]
https://twitter.com/davecheney/status/431581286918934528

**Comment by proppy** [comment]
We don't need it, but is it actually harmful ? :)

**Comment by tianon** [comment]
Not harmful to the end result, but Dave's sad. :smile:

**Comment by gmlewis** [comment]
The google/golang* Docker images have been deprecated in favor of the official Docker Go images:
https://hub.docker.com/_/golang/
Closing issue.
