### ISSUE TITLE
Please update to Go 1.6.3

### ISSUE THREAD

**Issue by nathany** [GoogleCloudPlatform/golang-docker#43]
Go 1.6.1 includes some security fixes.
https://groups.google.com/forum/#!msg/golang-announce/9eqIHqaWvck/kXsfO0ogLAAJ

GO_WRAPPER_COMMIT should to be updated to d7e2a8d90a9b8f5dfd5bcd428e0c33b68c40cc19
https://github.com/docker-library/golang/commits/master

Thanks.

P.S. The CLA links go to code.google.com which redirect to https://cla.developers.google.com. May want to update those links.

**Comment by broady** [comment]
Now `go1.6.2` (and soon `go1.7`)

**Comment by broady** [comment]
#46

**Comment by okdave** [comment]
Now `go1.6.3`

**Comment by broady** [comment]
BTW, this was pushed yesterday. `latest` now points to a version with Go 1.6.3.

FWIW, none of the security fixes in 1.6.x were relevant on App Engine.
