### ISSUE TITLE
Add end-to-end tests

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/golang-docker#45]
We should add some end-to-end tests.
1. Build the base image
2. Use it to build an image with some predefined code
3. Run the code and check the behaviour/output.

**Comment by cybrcodr** [comment]
We now have integration tests for the new runtime builder -- https://github.com/GoogleCloudPlatform/golang-docker/tree/master/runtime-builder/tests/integration.

We don't have support for cgo.  Feel free to file another issue if cgo is desired.
