### ISSUE TITLE
stackdriver debug broke hello world

### ISSUE THREAD

**Issue by hraban** [GoogleCloudPlatform/golang-docker#60]
steps to reproduce:

0. checkout 54e58ac
1. `docker build -t golang ./base`
2. clone helloworld
3. add a Dockerfile:
```Dockerfile
FROM golang

COPY . /go/src/app
RUN go-wrapper install -tags appenginevm
```
4. change runtime to `custom` in app.yaml
5. `aedeploy docker build -t helloworld`
6. `docker run --rm helloworld`:
```
+ which app
+ exec go-cloud-debug -sourcecontext ./source-context.json -appmodule default -appversion default -- /go/bin/app
2016/12/30 17:02:02 Debuglet initialization: metadata: GCE metadata "project/numeric-project-id" not defined
2016/12/30 17:02:02 Debuglet initialization: metadata: GCE metadata "project/project-id" not defined
2016/12/30 17:02:02 Reading source context file: reading file "./source-context.json": open ./source-context.json: no such file or directory
2016/12/30 17:02:02 Error connecting to Cloud Debugger: google.DefaultTokenSource: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

If I do this one commit before current head (i.e. e3fa19c) it works without problems.

I get the same error when I actually deploy to ae using `aedeploy gcloud app deploy`.

**Comment by shantuo** [comment]
We released the new GCP image after the holiday, so `gcloud app deploy` should work now. `aedeploy` is deprecated. Could you share a little bit more about your use case?

**Comment by hraban** [comment]
It works now. What I'm trying to do is use this base image with the AE flex golang hello world example. I.e.: get hello world running with this base image.

So follow the steps on <https://cloud.google.com/go/getting-started/hello-world>, but instead of `runtime: go` in your app.yaml you have `runtime: custom`. Then have a Dockerfile with:
```Dockerfile
FROM gcr.io/google_appengine/golang

COPY . /go/src/app
RUN go-wrapper install -tags appenginevm
```
and gcloud app deploy. I now see that a source-context.json file appears in the working directory of the container when deployed on app engine. How is that done, though? Where do those files come from? How can I run this container locally? I used to be able to just `docker build -t myapp . ; docker run ... myapp`, but that doesn't create the source-context(s).json files, so now it breaks.

About this:

> aedeploy is deprecated.

Since when? Where was this announced? How can I set myself up to know these kind of things in the future? Is there a low-noise mailing list? A central, source-of-truth doc that I can trust if it contradicts other docs?

---

> To deploy a Go app, use the aedeploy tool, which will correctly assemble your app's dependencies in the same way that the go tool does.

– https://cloud.google.com/appengine/docs/flexible/go/testing-and-deploying-your-app

> To deploy your app to the App Engine flexible environment:
> 1. Deploy the Hello World app by running the following command from the helloworld directory:
>
>     $ aedeploy gcloud app deploy

– https://cloud.google.com/go/getting-started/hello-world

---

There was even a note, somewhere, in one of these bazillion docs and READMEs, that eventhough go1.6/7 introduced vendoring you should keep using aedeploy... But I can't find it at the moment.

The scatterbrain that is appengine docs can be a thicket worthy of guarding a Sleeping Beauty, at times. :P
