### ISSUE TITLE
Running docker images locally (cont'd #60)

### ISSUE THREAD

**Issue by hraban** [GoogleCloudPlatform/golang-docker#61]
Opening a new issue to keep these clean and self contained. Continuing from #60 : how do you run a custom built docker image locally? Now that it uses go-cloud-debug and source-context.json, which is not created when I do `docker run myapp`, I can't run the image outside the app engine. Which was a pretty dandy feature to have.

( @shantuo )

**Comment by shantuo** [comment]
I understand, I will disable the debugger when the source context and credentials are absent.

Both source context and credentials are generated during gcloud app deploy and stored in the image uploaded.

**Comment by hraban** [comment]
Thanks for that, man!
