### ISSUE TITLE
Tagging versions?

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/golang-docker#68]
Is there a way to see what versions are available? It looks like docs offer images without any tags.

When I pulled `gcr.io/google-appengine/golang` I observed that it is go1.6.3, but go1.8 is now available. Is it because this image is designed for App Engine or is there some other reason?

**Comment by cybrcodr** [comment]
GCR has not been updated yet.  I can update this thread when it gets updated.

**Comment by ahmetb** [comment]
Which image are you referring to?

**Comment by cybrcodr** [comment]
I was referring to the GCR image gcr.io/google-appengine/golang which is accessible via the gcloud tool.

The latest version is now 1.8.

**Comment by ahmetb** [comment]
Ah got it. I am new to all this. I guess my 2 questions:

1. Do we always have :latest instead of :1.6, :1.7, :1.8?
2. How do you access that image via gcloud

**Comment by cybrcodr** [comment]
1. Yes.  I think w/o specifying a tag, it will fetch the latest.
2. To fetch the Docker image ...
$ gcloud docker -- pull gcr.io/google_appengine/golang:latest

**Comment by ahmetb** [comment]
> Yes. I think w/o specifying a tag, it will fetch the latest.

I understand, but my question was more like, do we have tags at all or is it only :latest? I am asking this because don't see any tags like :1.6 or :1.8 documented/listed anywhere (in README at least) so I am assuming :latest is the only tag that exists?

> $ gcloud docker -- pull gcr.io/google_appengine/golang:latest

Ah got it, then `docker pull gcr.io/google_appengine/golang:latest` works just fine without gcloud too. I got confused for a moment when you said "accessible via gcloud". I think it's just a public image accessible from anything that can pull Docker images.

**Comment by cybrcodr** [comment]
> I understand, but my question was more like, do we have tags at all or is it only :latest? I am asking this because don't see any tags like :1.6 or :1.8 documented/listed anywhere (in README at least) so I am assuming :latest is the only tag that exists?

Yeah, we didn't document that.  You can see all the tags by running ...

`gcloud beta container images list-tags gcr.io/google_appengine/golang
`

We'll make sure to have the major version tag so users can use that to pin a particular version.

> Ah got it, then docker pull gcr.io/google_appengine/golang:latest works just fine without gcloud too. I got confused for a moment when you said "accessible via gcloud". I think it's just a public image accessible from anything that can pull Docker images.

Good to know.  I didn't know that docker can pull directly from GCR.  I'm new at this too:)
