### ISSUE TITLE
Alpine-based image?

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/golang-docker#69]
Is there a plan to offer an alpine-based (smaller) alternative for this base image, like `docker.io/library/golang:1.8-alpine`?

**Comment by broady** [comment]
Yes. Actually, lighter than Alpine.

**Comment by cybrcodr** [comment]
The current beta build pipeline produces the app image with [distroless/base](https://github.com/GoogleCloudPlatform/distroless/tree/master/base) image as the base.

Read the following announcement --
https://groups.google.com/forum/#!msg/google-appengine-go/cG_JAAX73Zg/27wXKI7aBQAJ

The runtime-builder directory for this repo contains the sources for the new build pipeline.  It utilizes [Google Cloud Container Builder](https://cloud.google.com/container-builder/docs/) for doing the builds.
